-- 코드를 입력하세요
SELECT UGB.TITLE, UGB.BOARD_ID, UGR.REPLY_ID, UGR.WRITER_ID, UGR.CONTENTS, DATE_FORMAT(UGR.CREATED_DATE, "%Y-%m-%d") as CREATED_DATE
from USED_GOODS_BOARD as UGB
INNER JOIN USED_GOODS_REPLY as UGR
ON UGB.BOARD_ID = UGR.BOARD_ID 
where DATE_FORMAT(UGB.CREATED_DATE, '%Y-%m') = '2022-10'
order by UGR.CREATED_DATE ASC, UGB.TITLE ASC