-- 코드를 입력하세요
SELECT APP.APNT_NO, P.PT_NAME, P.PT_NO, D.MCDP_CD, D.DR_NAME, APP.APNT_YMD
FROM APPOINTMENT APP
JOIN PATIENT P
ON APP.PT_NO = P.PT_NO
JOIN DOCTOR D
ON APP.MDDR_ID = D.DR_ID
WHERE D.MCDP_CD LIKE 'CS'
AND APNT_CNCL_YN LIKE 'N'
AND YEAR(APNT_YMD) = 2022
AND MONTH(APNT_YMD) = 4
AND DAY(APNT_YMD) = 13
ORDER BY APP.APNT_YMD;