-- 코드를 작성해주세요
SELECT FI.ID, FN.FISH_NAME, MAXFI.LEN LENGTH
FROM FISH_INFO FI JOIN FISH_NAME_INFO FN
ON FI.FISH_TYPE = FN.FISH_TYPE
JOIN
(SELECT FISH_TYPE, MAX(LENGTH) LEN
FROM FISH_INFO
GROUP BY FISH_TYPE) MAXFI
ON FI.FISH_TYPE = MAXFI.FISH_TYPE
WHERE FI.LENGTH = MAXFI.LEN
ORDER BY ID;