SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM FISH_INFO I 
JOIN FISH_NAME_INFO N
# ON I.FISH_TYPE = N.FISH_TYPE
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) LENGTH
    FROM FISH_INFO
    WHERE LENGTH IS NOT NULL 
    GROUP BY FISH_TYPE
) M
ON I.FISH_TYPE = N.FISH_TYPE AND I.FISH_TYPE = M.FISH_TYPE
WHERE I.LENGTH = M.LENGTH
ORDER BY I.ID;