SELECT COUNT(*) FISH_COUNT, MAX(LENGTH) MAX_LENGTH, FISH_TYPE
FROM (
    SELECT FISH_TYPE, IFNULL(LENGTH, 10) LENGTH
    FROM FISH_INFO
) FIX_FISH_INFO
GROUP BY FISH_TYPE
HAVING 33 < AVG(LENGTH)
ORDER BY FISH_TYPE